Update CONTRIBUTING.md
kuzzleio/kuzzle pull request #1789
Opened 2020-09-23 09:49 UTC by scottinet

# Description

Update/modernize the CONTRIBUTING.md file

# Other changes

Expose Kuzzle's MQTT port to allow functional tests to be run from outside docker images.

2020-09-23 10:05 UTC, Leodau requested changes
Just some anti OCD for me.

2020-09-23 10:05 UTC, Leodau commented on CONTRIBUTING.md
> +You can now access to the Kuzzle HTTP/WebSocket API through the following URL: `http://localhost:7512`.
```suggestion
You can now access the Kuzzle HTTP/WebSocket API through the following URL: `http://localhost:7512`.
```

2020-09-23 10:05 UTC, Leodau commented on CONTRIBUTING.md
> +# wait for Kuzzle stack to be up, and start the entire test suite (long)
```suggestion
# Wait for Kuzzle stack to be up, and start the entire test suite (long)
```

2020-09-23 10:05 UTC, Leodau commented on CONTRIBUTING.md
> +# start a kuzzle cluster with development tools enabled
```suggestion
# Start a kuzzle cluster with development tools enabled
```

2020-09-24 07:37 UTC, Leodau approved these changes

2020-09-30 08:10 UTC, Aschen approved these changes

2020-09-30 08:10 UTC, merged