Add documentation - Getting Started : Access Control RIghts
kuzzleio/kuzzle pull request #1813
Opened 2020-10-13 12:30 UTC by Aschen

2020-10-13 12:58 UTC, scottinet requested changes

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +As in any backend, Kuzzle allows you to restrict access to its functionalities according to the users.
```suggestion
As in any backend, Kuzzle allows you to restrict access to its features, depending on the querying users.
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> + - **role**: whitelist authorized API actions
```suggestion
 - **role**: whitelist of allowed API actions
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +First, we are gonna create a new role with the [security:createRole](/core/2/api/controllers/security/create-role) action.
```suggestion
First, we are going to create a new role with the [security:createRole](/core/2/api/controllers/security/create-role) action.
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +The following role description give access to [auth:getCurrentUser](/core/2/api/controllers/auth/get-current-user) and [server:info](/core/2/api/controllers/auth/get-current-user) actions only.
```suggestion
The following role description gives access to [auth:getCurrentUser](/core/2/api/controllers/auth/get-current-user) and to the [server:info](/core/2/api/controllers/auth/get-current-user) actions only.
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +Copy the above role and then run this command: `kourou security:createRole --id hostes --body-editor`
Why that id? I don't get it :thinking:

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +A text editor should open itself, replace the existing body by our role definition and then exit the editor.
```suggestion
A text editor should open itself: replace the existing body by the copied role definition and then exit the editor.
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +Then, we are gonna create a profile who use our newly created role. For this we will use the [security:createProfile](/core/2/api/controllers/security/create-profile) action.
```suggestion
Then, we are going to create a profile which uses our newly created role. For this we will use the [security:createProfile](/core/2/api/controllers/security/create-profile) action.
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +Now we have a `hostes` profile which give access to the `hostes` role actions.
```suggestion
Now we have a `hostes` profile which gives access to the API actions allowed by the `hostes` role.
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +Finally, we need an user that use the `hostes` profile. The API action to create an user is [security:createUser](/core/2/api/controllers/security/create-user).
```suggestion
Finally, we need a user attached the `hostes` profile. The API action to create a user is [security:createUser](/core/2/api/controllers/security/create-user).
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +User need at least to be assigned with one profile. Also we are gonna give our user some credentials to be able to log in.
```suggestion
Users need to have at least one assigned profile. We also will have to give our user some credentials to be able to log in with it.
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +### Creates administrator and restrict anonymous user rights
```suggestion
### Creating an administrator account, and restricting anonymous user rights
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +When you are not authenticated, your request are executed as the `anonymous` user.
```suggestion
When you are not authenticated, your requests are executed as the `anonymous` user.
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +Like every other user, this user is assigned with a profile (`anonymous`) and thus a role (`anonymous` as well).
```suggestion
As with any other user, the `anonymous` user has a profile assigned (named `anonymous`), and thus a role (named `anonymous` as well).
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +By default, the `anonymous` role give access to every API actions. This is intended to makes development easier but it's definitively not suitable for production.
```suggestion
By default, the `anonymous` role gives access to all API actions. This is intended to make development easier, but it's definitively not suitable for production.
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +It's recommanded to use the [security:createFirstAdmin](/core/2/api/controllers/security/create-first-admin) action to creates an admin and restrict anonymous user rights.
```suggestion
It's recommended to use the [security:createFirstAdmin](/core/2/api/controllers/security/create-first-admin) action to create an administrator user, and to restrict anonymous user rights.
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +The [security:createFirstAdmin](/core/2/api/controllers/security/create-first-admin) creates an user which have the `admin` profile and this the `admin` role who give access to every API actions.
```suggestion
The [security:createFirstAdmin](/core/2/api/controllers/security/create-first-admin) creates a user attached to the `admin` profile, which uses the `admin` role, giving access to all API actions.
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +In this way you can always access the complete API throught this admin account.
```suggestion
This way you can always access the complete API through this admin account.
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +You should get the following error because since the anonymous user is now restricted to only a few API actions:
```suggestion
You should get the following error because now the anonymous user is restricted to only a few API actions:
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +#### Try the API as authentified user
```suggestion
#### Try the API as an authenticated user
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +#### Try the API as anonymous user
```suggestion
#### Try the API as the anonymous user
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +Run the same command but authenticate with the user we just create: `kourou server:now --username yagmur --password password`
```suggestion
Run the same command, authenticating with the user we just created: `kourou server:now --username yagmur --password password`
```

2020-10-13 12:58 UTC, scottinet commented on doc/2/guides/getting-started/3-access-control-rights/index.md
> +We have the right to use this API action because we are now authenticated.
```suggestion
We are allowed to use this API action because we are now authenticated with a user with sufficient rights.
```

2020-10-14 14:56 UTC, Njuelle approved these changes

2020-10-15 13:53 UTC, merged