Add documentation - Getting Started - Harmonization
kuzzleio/kuzzle pull request #1834
Opened 2020-10-21 11:34 UTC by Aschen

2020-10-21 12:08 UTC, scottinet approved these changes

2020-10-21 12:08 UTC, scottinet commented on doc/2/guides/getting-started/2-storing-and-accessing-data/index.md
> +The **collections have mappings** that characterize the way Elasticsearch will index the data for the search.
```suggestion
The **collections have mappings** that characterize the way Elasticsearch will index the data for searches.
```

2020-10-21 14:42 UTC, xbill82 commented on doc/2/guides/getting-started/1-quick-start/index.md
> +The Admin Console is a [Single Page Application](https://www.wikiwand.com/en/Single-page_application) written in Vue.js and using the [Javascript SDK](/sdk/js/7).
```suggestion
The Admin Console is a [Single Page Application](https://www.wikipedia.org/en/Single-page_application) written in Vue.js and using the [Javascript SDK](/sdk/js/7).  
```

2020-10-21 14:44 UTC, xbill82 commented on doc/2/guides/getting-started/2-storing-and-accessing-data/index.md
> +The **collections have mappings** that characterize the way Elasticsearch will index the data for searches.
```suggestion
The **collections have mappings** that define the way Elasticsearch will index the data for searches.
```

2020-10-21 15:17 UTC, Aschen commented on doc/2/guides/getting-started/1-quick-start/index.md
> +The Admin Console is a [Single Page Application](https://www.wikiwand.com/en/Single-page_application) written in Vue.js and using the [Javascript SDK](/sdk/js/7).
Ah yes! Ok but wikiwand is so good <3

2020-10-22 10:09 UTC, xbill82 approved these changes

2020-10-23 11:47 UTC, Njuelle requested changes

2020-10-23 11:47 UTC, Njuelle commented on doc/2/guides/getting-started/6-understand-application-development/index.md
> +Une fois l'application dans l'état démarrée, elle propose des méthodes pour intéragir avec votre application Kuzzle.
there's french here ;)

2020-10-23 11:47 UTC, Njuelle commented on doc/2/guides/getting-started/6-understand-application-development/index.md
> +You can acces it through the [Backend.sdk] property.
missing link?

2020-10-23 11:50 UTC, Njuelle commented on doc/2/guides/getting-started/6-understand-application-development/index.md
> +When my application is in the instanciated state, it exposes methods to **register new features** in Kuzzle core, like:
```suggestion
When the application is in the instanciated state, it exposes methods to **register new features** in Kuzzle core, like:
```

2020-10-23 11:58 UTC, jenow approved these changes

2020-10-23 13:09 UTC, scottinet requested changes

2020-10-23 13:09 UTC, scottinet commented on doc/2/guides/getting-started/9-deploy-your-application/index.md
> +The only specifity is that **Kuzzle needs to compile C and C++ dependencies** so the `npm install` will also be looking for `python`, `make` and `g++` packages.
```suggestion
The only specifity is that **Kuzzle needs to compile C and C++ dependencies** so the `npm install` will also be looking for the `python`, `make` and `g++` packages.   
```

2020-10-23 14:12 UTC, Aschen commented on doc/2/guides/getting-started/6-understand-application-development/index.md
> +- [realtime](/sdk/js/7/controllers/realtime)
Actually every controllers can be accessed now :sweat_smile:

2020-10-23 14:16 UTC, alexandrebouthinon approved these changes
I know this is not in the current diff but we should format this WebSocket response https://github.com/kuzzleio/kuzzle/blame/56b77ceffa54fe525390c1cf57b9ad68afb8b332/doc/2/guides/getting-started/7-create-new-controllers/index.md#L90

2020-10-23 14:27 UTC, Leodau requested changes

2020-10-23 14:27 UTC, Leodau commented on doc/2/guides/getting-started/6-write-application/index.md
> + - and more..!
```suggestion
 - Use the [Embedded SDK](/core/2/some-link) to use the API
 - Trigger Events
 - Log Messages
 - And much more!
```

2020-10-23 14:31 UTC, Aschen commented
@scottinet Should we start list items by a capital letter?

```
Hello:
 - We are
 - In a List
```

Instead of
```
Hello:
 - we are
 - in a list
```

2020-10-23 14:38 UTC, Leodau requested changes

2020-10-23 14:38 UTC, Leodau commented on doc/2/guides/getting-started/6-write-application/index.md
> +    // interact with Kuzzle API to create a new index if it does not already exist
```suggestion
    // Interact with Kuzzle API to create a new index if it does not already exist
```

2020-10-23 14:38 UTC, Leodau commented on doc/2/guides/getting-started/6-write-application/index.md
> +// after application startup
```suggestion
// After application startup
```

2020-10-23 14:38 UTC, Leodau commented on doc/2/guides/getting-started/6-write-application/index.md
> +// creates a document
```suggestion
// Creates a document
```

2020-10-23 14:38 UTC, Leodau commented on doc/2/guides/getting-started/6-write-application/index.md
> +// after application startup
```suggestion
// After application startup
```

2020-10-23 14:38 UTC, Leodau commented on doc/2/guides/getting-started/6-write-application/index.md
> +// execute a custom controller action
```suggestion
// Execute a custom controller action
```

2020-10-23 14:38 UTC, Leodau commented on doc/2/guides/getting-started/6-write-application/index.md
> +// instantiate an application
```suggestion
// Instantiate an application
```

2020-10-23 14:38 UTC, Leodau commented on doc/2/guides/getting-started/6-write-application/index.md
> +// now we can register features
```suggestion
// Now we can register features
```

2020-10-23 14:38 UTC, Leodau commented on doc/2/guides/getting-started/6-write-application/index.md
> +// register a new controller
```suggestion
// Register a new controller
```

2020-10-23 14:38 UTC, Leodau commented on doc/2/guides/getting-started/6-write-application/index.md
> +// start the application
```suggestion
// Start the application
```

2020-10-23 14:38 UTC, Leodau commented on doc/2/guides/getting-started/6-write-application/index.md
> +    // interact with Kuzzle API to creates a new index if it does not exists
```suggestion
    // Now we can interact with Kuzzle API to create a new index if it does not exists
```

2020-10-27 11:13 UTC, scottinet requested changes
a few minor changes, otherwise it looks good to me

2020-10-27 11:13 UTC, scottinet commented on doc/2/guides/getting-started/1-run-kuzzle/index.md
> + - Compile toolchain: g++, make and python
```suggestion
 - Compile toolchain: a C++ compiler (g++, clang, ...), make and python
```

2020-10-27 11:13 UTC, scottinet commented on doc/2/guides/getting-started/2-store-and-access-data/index.md
> +# Store and access Data
```suggestion
# Store and Access Data
```

2020-10-27 11:13 UTC, scottinet commented on doc/2/guides/getting-started/2-store-and-access-data/index.md
> +Elasticsearch is primarly designed to be a search engine, so there are limitations when using it as a database.
```suggestion
Elasticsearch is primarily designed to be a search engine, so there are limitations when using it as a database.  
```

2020-10-27 11:13 UTC, scottinet commented on doc/2/guides/getting-started/9-deploy-your-application/index.md
> +The only specifity is that **Kuzzle needs to compile C and C++ dependencies** so a successful `npm install` execution needs the `python`, `make` and `g++` packages.
```suggestion
The only specifity is that **Kuzzle needs to compile C and C++ dependencies** so a successful `npm install` execution needs the `python` and `make` packages, as well as C and C++ compilers (in the following examples we'll use `g++`).   
```

2020-10-27 13:06 UTC, scottinet approved these changes

2020-10-28 08:12 UTC, Leodau approved these changes

2020-10-28 09:36 UTC, merged