Add Plugin
kuzzleio/kuzzle pull request #1844
Opened 2020-10-28 13:52 UTC by Aschen

2020-10-29 16:27 UTC, xbill82 approved these changes

2020-10-29 16:27 UTC, xbill82 commented on doc/2/guides/develop-on-kuzzle/4-external-plugins/index.md
> +Kuzzle allows to add **whole set of features via plugins**.
```suggestion
You can **extend Kuzzle's features** via plugins.
```

2020-10-29 16:27 UTC, xbill82 commented on doc/2/guides/develop-on-kuzzle/4-external-plugins/index.md
> +Plugins are **intended to be reused** between several applications by proposing generic functionalities.
```suggestion
Plugins are **intended to be reused** between several applications by proposing generic features.
```

2020-10-29 16:27 UTC, xbill82 commented on doc/2/guides/develop-on-kuzzle/4-external-plugins/index.md
> +There are 3 categories of functionalities for plugins:
```suggestion
Plugins allow you to achieve three main goals:
```

2020-11-02 10:18 UTC, scottinet requested changes

2020-11-02 10:18 UTC, scottinet commented on doc/2/guides/develop-on-kuzzle/4-external-plugins/index.md
> +These feature categories are not exclusive and although it is not recommended, a plugin can embed features belonging to the 3 categories.
nope: plugins and protocols are different objects, with separate directories

2020-11-02 10:18 UTC, scottinet commented on doc/2/guides/develop-on-kuzzle/4-external-plugins/index.md
> +In addition to the standard features available in an application, plugins can also integrate [authentication strategies](/core/2/some-link) and [network protocols](/core/2/some-link).
nope, plugins can't add new network protocols, only protocols can

```suggestion
In addition to the standard features available in an application, plugins can also integrate [authentication strategies](/core/2/some-link) and [network protocols](/core/2/some-link).
```

2020-11-02 11:23 UTC, alexandrebouthinon approved these changes

2020-11-02 14:11 UTC, xbill82 approved these changes

2020-11-03 06:54 UTC, merged