Rewrite documentation - Main Concepts - Realtime Engine
kuzzleio/kuzzle pull request #1847
Opened 2020-10-29 13:17 UTC by Aschen

https://deploy-preview-1845--doc-kuzzle.netlify.app/guides/main-concepts/5-realtime-engine

2020-10-30 14:35 UTC, Njuelle approved these changes

2020-11-02 09:19 UTC, scottinet requested changes

2020-11-02 09:19 UTC, scottinet commented on doc/2/guides/introduction/1-what-is-kuzzle/index.md
> +Whether you want to ask a question about [StackOverflow](https://stackoverflow.com/questions/ask?tags=kuzzle), check out the [Kuzzle awesome list](https://github.com/kuzzleio/awesome-kuzzle), watch o
```suggestion
Whether you want to ask a question on [StackOverflow](https://stackoverflow.com/questions/ask?tags=kuzzle), check out the [Kuzzle awesome list](https://github.com/kuzzleio/awesome-kuzzle), watch our video on [YouTube](https://www.youtube.com/channel/UCHcEzVQoH10YSyxc7jD3SMw/videos), or discuss Kuzzle on [Discord](http://join.discord.kuzzle.io), the community and the core team will be there to help you.
```

2020-11-02 09:19 UTC, scottinet commented on doc/2/guides/main-concepts/5-realtime-engine/index.md
> +Realtime capabilities requires the use of a **persistent communication protocol** such as WebSocket or MQTT.
```suggestion
Realtime capabilities require the use of a **persistent communication protocol** such as WebSocket or MQTT.
```

2020-11-02 09:19 UTC, scottinet commented on doc/2/guides/main-concepts/5-realtime-engine/index.md
> + - A second client client posts a message in this room,
```suggestion
 - A second client posts a message in that room,
```

2020-11-02 09:19 UTC, scottinet commented on doc/2/guides/main-concepts/5-realtime-engine/index.md
>  When changes occur on this collection (eg: document creation, modification or deletion), Kuzzle will send notifications to the corresponding subscribers.
```suggestion
When changes occur on this collection (e.g. document creation, modification or deletion), Kuzzle will send notifications to the corresponding subscribers.
```

2020-11-02 09:19 UTC, scottinet commented on doc/2/guides/main-concepts/5-realtime-engine/index.md
> +# Subscribe to database notifications
```suggestion
# Subscribes to database notifications
```

2020-11-02 09:19 UTC, scottinet commented on doc/2/guides/main-concepts/5-realtime-engine/index.md
> +When a client subscribes to realtime notifications, whether in Pub/Sub or Database Notification, he can **specify a set of subscription filters**.
```suggestion
When a client subscribes to realtime notifications, whether in Pub/Sub or Database Notification, they can **specify a set of subscription filters**.
```

2020-11-02 09:19 UTC, scottinet commented on doc/2/guides/main-concepts/5-realtime-engine/index.md
> +Then, in another terminal you can publishes a message in the room specifying volatile data:
```suggestion
Then, in another terminal you can publish a message in the room specifying volatile data:
```

2020-11-02 09:26 UTC, scottinet approved these changes

2020-11-02 11:21 UTC, alexandrebouthinon approved these changes

2020-11-02 13:53 UTC, xbill82 approved these changes
Wording nitpikking

2020-11-02 13:53 UTC, xbill82 commented on doc/2/guides/main-concepts/5-realtime-engine/index.md
> +Kuzzle includes his **own high-performance Realtime Engine** for sending notifications to clients connected through the API.
```suggestion
Kuzzle is shipped with its own **high-performance Realtime Engine** for sending notifications to clients connected through the API.
```

2020-11-02 13:53 UTC, xbill82 commented on doc/2/guides/main-concepts/5-realtime-engine/index.md
> +Each client who subscribes to the room will receive the following notification:
```suggestion
Each client subscribing to the room will receive the following notification:
```

2020-11-02 13:53 UTC, xbill82 commented on doc/2/guides/main-concepts/5-realtime-engine/index.md
> +SDKs and Kourou use volatile data to send additional informations like the client name or version.
```suggestion
SDKs and Kourou use volatile data to send additional information like the client name or version.
```

2020-11-03 06:57 UTC, merged