Fix index:mDelete to make it return the list of deleted indexes
kuzzleio/kuzzle pull request #1858
Opened 2020-11-03 10:16 UTC by scottinet

# Description

As the title says: calling `index:mDelete` resulted in an empty response value, instead of an expected array of deleted indexes.

This bug is live since Kuzzle@2.6.0

2020-11-03 10:17 UTC, jenow approved these changes

2020-11-03 10:25 UTC, alexandrebouthinon requested changes

2020-11-03 10:25 UTC, alexandrebouthinon commented on test/core/storage/clientAdapter.test.js
> +    describe.only('#index:mDelete', () => {
```suggestion
    describe('#index:mDelete', () => {
```

2020-11-03 10:41 UTC, Yoann-Abbes approved these changes

2020-11-04 14:31 UTC, alexandrebouthinon approved these changes

2020-11-04 14:32 UTC, merged