Add documentation - Advanced - API Keys
kuzzleio/kuzzle pull request #1878
Opened 2020-11-20 12:58 UTC by Aschen

https://deploy-preview-1863--doc-kuzzle.netlify.app/guides/advanced/2-api-keys

2020-11-23 16:18 UTC, jenow requested changes

2020-11-23 16:18 UTC, jenow commented on doc/2/guides/advanced/2-api-keys/index.md
> +An API key is associated with a standard [authentication token](/core/2/guides/main-concepts/5-authentication#authentication-token) that can then be used to [authenticate users] to the Kuzzle API.
There is a link missing at `[authenticate users]`

2020-11-24 10:29 UTC, scottinet requested changes

2020-11-24 10:29 UTC, scottinet commented on doc/2/guides/advanced/1-secrets-vault/index.md
> +description: Security store your application secrets
```suggestion
description: Securely store your application secrets
```

2020-11-24 10:29 UTC, scottinet commented on doc/2/guides/advanced/2-api-keys/index.md
> +## Create API Key
```suggestion
## Create an API Key
```

2020-11-24 10:29 UTC, scottinet commented on doc/2/guides/advanced/2-api-keys/index.md
> +The authentication token `token` will never be returned by Kuzzle again. If you lose it, you'll have to delete the API key and recreate a new one.
```suggestion
The authentication token provided in the `token` property will never be returned by Kuzzle again. If you lose it, you'll have to delete the API key and recreate a new one.
```

2020-11-24 10:29 UTC, scottinet commented on doc/2/guides/advanced/2-api-keys/index.md
> +## Search for API Key
```suggestion
## Search for API Keys
```

2020-11-24 10:29 UTC, scottinet commented on doc/2/guides/advanced/2-api-keys/index.md
> +In order to know to which API key an authentication token corresponds, it is possible to use the `fingerprint` property which corresponds to the SHA256 hash of the token.
```suggestion
In order to know to which API key an authentication token corresponds, it is possible to use the `fingerprint` property which is a SHA256 hash of the token.
```

2020-11-24 10:29 UTC, scottinet commented on doc/2/guides/advanced/2-api-keys/index.md
> +It is possible to use [auth:deleteApiKey](/core/2/references/controllers/auth/delete-api-key) and [security:deleteApiKey](/core/2/references/controllers/security/delete-api-key) methods to delete API
```suggestion
It is possible to use the [auth:deleteApiKey](/core/2/references/controllers/auth/delete-api-key) and the [security:deleteApiKey](/core/2/references/controllers/security/delete-api-key) methods to delete API keys.
```

2020-11-24 10:33 UTC, jenow approved these changes

2020-11-26 08:10 UTC, xbill82 approved these changes

2020-11-26 08:10 UTC, xbill82 commented on doc/2/guides/advanced/2-api-keys/index.md
> +Administrators can create API keys for users using the [security:createApiKey](/core/2/references/controllers/security/create-api-key) action.
```suggestion
Administrators can create API keys for other users using the [security:createApiKey](/core/2/references/controllers/security/create-api-key) action.
```

2020-11-26 08:20 UTC, scottinet approved these changes

2020-11-26 11:21 UTC, merged