Fix plugin name inferring
kuzzleio/kuzzle pull request #1947
Opened 2021-01-28 08:08 UTC by Aschen

## What does this PR do ?

Plugin name are inferred from the class name converted to `kebab-case`. 

For example `DeviceManagerPlugin` will give `device-manager-plugin`. 

The `plugin` suffix or prefix is redundant and should be removed from the inferred name. 

### Boyscout

 - extract class `BackendPlugin` in it's own file

2021-01-29 14:18 UTC, Leodau requested changes
Extracting the **BackendPlugin** seems like **more** than just a _Boyscout_ given this PR's size.

2021-01-29 14:18 UTC, Leodau commented on doc/2/guides/develop-on-kuzzle/external-plugins/index.md
> +  - the string `Plugin` will be removed
Ultra nit, I can't stand lists not starting with caps. :crying_cat_face: 
```suggestion
  - Class name will be converted to `kebab-case`
  - The word `Plugin` will be removed
```

2021-01-29 14:18 UTC, Leodau commented on doc/2/guides/develop-on-kuzzle/external-plugins/index.md
> +The plugin default name will be inferred from the class name:
```suggestion
The plugin's default name will be inferred from the class name:
```

2021-01-29 14:18 UTC, Leodau commented on lib/core/backend/backendPlugin.ts
> +   *    - `name`: Specify plugin name instead of using the class name.
```suggestion
   *    - `name`: Specify a plugin name instead of using the class name.
```

2021-01-29 14:18 UTC, Leodau commented on test/core/backend/BackendPlugin.test.js
> +
```suggestion
```

2021-01-29 14:18 UTC, Leodau commented on test/core/backend/BackendPlugin.test.js
> +  });
```suggestion
```

2021-01-29 14:18 UTC, Leodau commented on test/core/backend/BackendPlugin.test.js
> +    it('should allows to use a plugin and infer the name', () => {
```suggestion
    it('should allow to use a plugin and infer the name', () => {
```

2021-01-29 14:18 UTC, Leodau commented on test/core/backend/BackendPlugin.test.js
> +    it('should allows to specify the plugin name and options', () => {
```suggestion
    it('should allow to specify the plugin's name and options', () => {
```

2021-01-29 14:18 UTC, Leodau commented on test/core/backend/BackendPlugin.test.js
> +    it('should throws an error if the plugin is invalid', () => {
```suggestion
    it('should throw an error if the plugin is invalid', () => {
```

2021-01-29 14:18 UTC, Leodau commented on test/core/backend/BackendPlugin.test.js
> +    it('should throws an error if the application is already started', () => {
```suggestion
    it('should throw an error if the application is already started', () => {
```

2021-01-29 14:18 UTC, Leodau commented on test/core/backend/BackendPlugin.test.js
> +      }).throwError({ id: 'plugin.runtime.already_started' });
I _kindda_ don't get this test, trying to directly change the `application.vault.file` while running the app generates and error, but why would this be added to **BackendPlugin** tests?

2021-02-01 15:43 UTC, rolljee approved these changes

2021-02-01 15:43 UTC, rolljee commented on lib/core/backend/index.ts
> +export * from './backendPlugin';
Missing new line

2021-02-02 17:25 UTC, xbill82 approved these changes

2021-02-03 08:30 UTC, scottinet approved these changes

2021-02-03 12:59 UTC, Leodau approved these changes

2021-02-03 13:16 UTC, merged