Implement searchUsersByCredentials
kuzzleio/kuzzle pull request #1948
Opened 2021-01-28 13:00 UTC by Leodau

## What does this PR do ?

- Implements the new `security:searchUsersByCredentials` action.
- Plugins can/should now implement their own custom user `search` function.

### Example
**Request:**
**POST** `http://localhost:7512/credentials/local/users/_search`
```json
{
    
  "bool": {
    "must": [
      {
        "match": {
          "_id":  "test@test.com"
        }
      }
    ]
  }
}
```

**Response:**
```json
{
  "action": "searchUsersByCredentials",
  "collection": null,
  "controller": "security",
  "error": null,
  "index": null,
  "node": "adamant-dijkstra-33028",
  "requestId": "4f570e54-8b4c-4d2b-92f3-c7b4561f35da",
  "result": {
    "hits": [
      {
        "algorithm": "sha512",
        "encryption": "hmac",
        "passwordHistory": [],
        "stretching": true,
        "kuid": "test",
        "userPassword": "5ba45b25587ceff6ae",
        "userSalt": "53d058d08402edcfe0b97",
        "pepper": false,
        "updater": "-1",
        "_kuzzle_info": {
          "author": null,
          "createdAt": 1611837823127,
          "updatedAt": null,
          "updater": null
        },
        "_id": "test@test.com"
      }
    ],
    "total": 1
  },
  "status": 200,
  "volatile": null
}
```

#### Todo

- [ ] Documentation
- [ ] Tests

### How should this be manually tested?

1. Have a kuzzle running
2. [Live Test Here](https://hoppscotch.io/?method=POST&url=http://localhost:7512&path=/credentials/local/users/_search&contentType=application/json&rawParams=%7B%0A%20%20%20%20%0A%20%20%22bool%22:%20%7B%0A%20%20%20%20%22must%22:%20%5B%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22match%22:%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22_id%22:%20%20%22test@test.com%22%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%0A%20%20%7D%0A%7D)

Closes #1676

2021-05-06 08:03 UTC, xbill82 commented on doc/2/api/controllers/security/search-users-by-credentials/index.md
> +URL: http://kuzzle:7512/credentials/<strategy>/users/_search
This URL seems weird to me, I'd rather look for something more similar to the classic user-search API endpoint, like `http://kuzzle:7512/users/_search`. Searching users is what this all is about, isn't it? 

But you probably got to this for some good reason: can anybody give me some context?

2021-05-13 17:30 UTC, Aschen requested changes
Few comments.
Also I think this method should accept Koncorde DSL as well as other search methods and pass the translated query to the plugin

2021-05-13 17:30 UTC, Aschen commented on doc/2/api/controllers/security/search-users-by-credentials/index.md
> +  "body": {
IMHO the body should be what we call a `searchBody`, to allows users to pass either `query` and/or `sort` properties

2021-05-13 17:30 UTC, Aschen commented on lib/api/controllers/securityController.js
> +  async searchUsersByCredentials(request) {
Nitpicking
```suggestion
  async searchUsersByCredentials (request) {
```

2021-05-13 17:30 UTC, Aschen commented on lib/api/controllers/securityController.js
> +    if ( !searchMethod ) {
Nitpicking: coding standards (we can discuss this)
```suggestion
    if (! searchMethod) {
```

2021-05-14 12:30 UTC, Leodau commented on doc/2/api/controllers/security/search-users-by-credentials/index.md
> +This method is not intended to be exposed to the end user because of sensitive data that represents an exhaustive list of users ids.
```suggestion
This method is not intended to be exposed to the end user. A full list of users ids should be considered as sensitive data.
```

2021-05-14 12:30 UTC, Leodau commented on doc/2/api/controllers/security/search-users-by-credentials/index.md
> +  - `...`: Other properties depend on the authentification strategy
```suggestion
  - `...`: Other properties depending on the authentification strategy
```

2021-05-18 07:04 UTC, Aschen approved these changes

2021-05-19 08:10 UTC, Leodau commented on doc/2/api/controllers/security/search-users-by-credentials/index.md
> +Since credentials depend on the authentification strategy, so do the search query.
```suggestion
Since credentials depend on the authentication strategy, so do the search query.
```

2021-05-19 08:10 UTC, Leodau commented on doc/2/api/controllers/security/search-users-by-credentials/index.md
> +  - `...`: Other properties depending on the authentification strategy
```suggestion
  - `...`: Other properties depending on the authentication strategy
```

2021-05-19 08:10 UTC, Leodau commented on doc/2/guides/write-plugins/integrate-authentication-strategy/index.md
> +| `searchBody` | [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/query-dsl.html) | A query concerning the authentification strategy credentials |
```suggestion
| `searchBody` | [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/query-dsl.html) | A query concerning the authentication strategy credentials |
```

2021-05-19 08:10 UTC, Leodau commented on doc/2/guides/write-plugins/integrate-authentication-strategy/index.md
> +  - `...`: __Non sensitive__ credentials specific to this authentification strategy
```suggestion
  - `...`: __Non sensitive__ credentials specific to this authentication strategy
```

2021-05-20 08:20 UTC, xbill82 commented on doc/2/api/controllers/security/search-users-by-credentials/index.md
> +URL: http://kuzzle:7512/credentials/<strategy>/users/_search
Ok makes a lot more sense

2021-05-20 08:32 UTC, xbill82 approved these changes

2021-05-20 15:03 UTC, MathieuVeber commented
IMHO we should wait on this [PR](https://github.com/kuzzleio/kuzzle-plugin-auth-passport-local/pull/76) to be ready so we can merge them at the same time.

2021-05-27 11:46 UTC, merged