Launch units and functional test with node 14.15.4
kuzzleio/kuzzle pull request #1971
Opened 2021-02-09 13:39 UTC by Yoann-Abbes

## What does this PR do ?

Since Node.js 14 is going to be in LTS the 27 october, we should add official support for it and start using it by default.

We need to run the unit tests and also the functional tests with Node.js 14

https://github.com/kuzzleio/kuzzle/issues/1850

### How should this be manually tested?

  - Step 1 :
  - Step 2 :
  - Step 3 :

### Other changes

### Boyscout

2021-02-09 15:41 UTC, Aschen commented on docker-compose.yml
>      - NODE_12_VERSION=12.13.0
Well, I know it's not yours but this version of node is not even present in our matrix `node-version: ['14.15.4', '12.16.3', '12.20.0']`

2021-02-09 15:44 UTC, Aschen commented
I think we should update the docker images as well (`docker/images/*`) but I'm not sure if it will be a breaking or not :thinking: 

What do you think @alexandrebouthinon ?

2021-05-17 08:38 UTC, alexandrebouthinon approved these changes

2021-05-17 08:43 UTC, Aschen requested changes
This need to be updated with the latest Node.js 14 version

2021-05-19 15:48 UTC, Shiranuit commented
Updated to use lastest NodeJS version (14.17.0)

2021-06-23 06:28 UTC, merged