Allows dynamic pipe registration
kuzzleio/kuzzle pull request #1996
Opened 2021-03-03 09:31 UTC by Aschen

## What does this PR do ?

Allows to dynamically register pipes.

When the application is already started, `app.pipe.register` can be used with the `dynamic: true` option to dynamically register a pipe.  
The method will returns a `pipeId` which can be then used later to unregistere the pipe with `app.pipe.unregister`.

Defining dynamic pipes at return need to maintain a state of the registered pipes so new nodes joining the cluster can also register the same pipes.  
This dynamic state management is not handled by Kuzzle so developers should implements their own state management routines.

This feature is meant to be left undocumented since it's quite and advanced usage and we didn't had other use cases than our Workflows plugin.

### How should this be manually tested?

  - Step 1 : Run functional tests

### Other changes

  - allows to register pipe handler who do not returns a promise since the `EventHandler` type allows it, otherwise the pipe never returns anything and the request get stucked.

2021-03-08 13:37 UTC, scottinet approved these changes

2021-03-08 14:17 UTC, alexandrebouthinon approved these changes

2021-03-08 16:30 UTC, alexandrebouthinon requested changes

2021-03-08 16:30 UTC, alexandrebouthinon commented on features/support/hooks.js
> +  if (process.env.KUZZLE_PROTOCOL !== 'websocket') {
```suggestion
  if (process.env.KUZZLE_PROTOCOL === 'http') {
```

2021-03-08 23:03 UTC, alexandrebouthinon approved these changes

2021-03-09 08:58 UTC, Leodau approved these changes

2021-03-09 09:22 UTC, merged