Implement requestResponse.makeRaw()
kuzzleio/kuzzle pull request #2017
Opened 2021-03-14 17:52 UTC by Leodau

## What does this PR do ?
Adds a **makeRaw** function in our **requestResponse** class in order to ease **response.raw** access.

`request.response.makeRaw()`

Closes #1658

2021-03-15 09:20 UTC, Aschen reviewed
IMHO this method should allows to set the `headers` and the `status` like the [setResult](https://docs.kuzzle.io/core/2/framework/classes/kuzzle-request/set-result/#arguments) method.

2021-03-15 17:25 UTC, Leodau commented
> IMHO this method should allows to set the `headers` and the `status` like the [setResult](https://docs.kuzzle.io/core/2/framework/classes/kuzzle-request/set-result/#arguments) method.
> 
> Also, the documentation should be updated accordingly the framework reference but also this page https://docs.kuzzle.io/core/2/guides/develop-on-kuzzle/api-controllers/#return-a-custom-response

I agree, but then.. **makeRaw()** would not be a good name for this then. 🤔

2021-03-16 07:01 UTC, Aschen commented
> I agree, but then.. **makeRaw()** would not be a good name for this then. thinking

I agree as well :sweat_smile: 
The purpose of this method is to send a custom response different from the standardized Kuzzle API response format.

For this we need to use the `raw` attribute so Kuzzle does not put the handler function return into the `result` property but we can also customize the HTTP headers and status.

(Again the HTTP protocol make everything more difficult :sweat_smile: )

2021-03-16 10:03 UTC, Leodau commented
> IMHO this method should allows to set the `headers` and the `status` like the [setResult](https://docs.kuzzle.io/core/2/framework/classes/kuzzle-request/set-result/#arguments) method.
> 
> Also, the documentation should be updated accordingly the framework reference but also this page https://docs.kuzzle.io/core/2/guides/develop-on-kuzzle/api-controllers/#return-a-custom-response

But why would we add a `request.response.f(header, status, isRaw)` to the class, IF what we are looking is to effectively remove the need of doing **request.setResult**???

2021-03-16 11:16 UTC, Aschen commented
> But why would we add a `request.response.f(header, status, isRaw)` to the class, IF what we are looking is to effectively remove the need of doing **request.setResult**???

Actually the `setResult` method is what we need. The only problem is that the first argument is supposed to be the action result but we set it to null because Kuzzle always use the handler function return

2021-03-16 12:08 UTC, scottinet commented
What about this?

```js
request.response.configure({
  headers?: JSONObject,
  status?: number,
  standardize?: boolean,
});
```

This is self-documented: this method configures the response.

The `standardize` option (name to be debated) replaces the `raw` one and instructs Kuzzle to standardize the response into a Kuzzle response one (default: `true`).

wdyt?

2021-03-16 17:31 UTC, Leodau commented
> What about this?
> 
> ```js
> request.response.configure({
>   headers?: JSONObject,
>   status?: number,
>   standardize?: boolean,
> });
> ```
> 
> This is self-documented: this method configures the response.
> 
> The `standardize` option (name to be debated) replaces the `raw` one and instructs Kuzzle to standardize the response into a Kuzzle response one (default: `true`).
> 
> Lastly: an option object instead of arguments, because I feel we might add more options in the future. But this is just a feeling, I might be mistaken on that one.
> 
> wdyt?

Awesome, I really like the `configure` idea.
Btw for the 'standardize' option, should we stay around the `raw: true` instead, so we don't have too many differences between **setResult** and **configure**?. 

> We could also, add the **standardize** option to **setResult** and deprecate 'raw'?

2021-03-17 05:57 UTC, Aschen commented
> Awesome, I really like the `configure` idea.
> Btw for the 'standardize' option, should we stay around the `raw: true` instead, so we don't have too many differences between **setResult** and **configure**?.
> 
> Or we could add the **standardize** option to **setResult** and deprecate 'raw'?

I agree with your proposal but I would go even further and deprecate the `setResult` method which was first meant to an internal usage I think.

2021-03-17 08:51 UTC, scottinet commented
> Awesome, I really like the `configure` idea.
> Btw for the 'standardize' option, should we stay around the `raw: true` instead, so we don't have too many differences between **setResult** and **configure**?.

Like @Aschen, I don't really care about `setResult`. We cannot deprecate it internally (we kinda need it), but its usage by users could, as setting a request's result should be handled solely by Kuzzle.

As for that option name:

* `raw`: I don't like it. And I did come up with that name :expressionless: 
* `standardize` is a tad better, but I'm not entirely convinced about it either

If you have a better name, either to mean that the response will be embedded in a standard Kuzzle response, or that it will be sent raw, don't hesitate to submit it :)

2021-03-17 10:35 UTC, Aschen commented
1) `standardize: true`
2) `standardResponse: true`
3) `format: "standard|raw"`

2021-03-17 11:07 UTC, scottinet commented
```js
request.response.configure({ asKuzzleResponse: false });
```

2021-03-17 12:24 UTC, Leodau commented
Ok, `format` it is then :partying_face: 

`request.response.configure({ format: 'standard|raw' });`

2021-03-18 19:31 UTC, Aschen commented
About the changelog, it's more an enhancement to me since the feature already exists

2021-03-21 12:40 UTC, alexandrebouthinon approved these changes

2021-03-21 13:29 UTC, Aschen requested changes

2021-03-21 13:29 UTC, Aschen commented on doc/2/framework/classes/request-response/configure/index.md
> +| Name | Type | Description                      | Default |
This is not how we document default option, you can look here for example https://github.com/kuzzleio/sdk-javascript/blob/master/doc/7/controllers/document/search/index.md#options

2021-03-21 13:29 UTC, Aschen commented on lib/api/request/requestResponse.ts
> +   * Configure the response
Missing jsdoc about the options object

2021-03-22 06:13 UTC, Aschen approved these changes

2021-03-22 06:13 UTC, Aschen commented on lib/api/request/requestResponse.ts
> +   * @param {String} [options.format] - Response format, standard or raw
```suggestion
   * @param [options]
   * @param [options.headers] - Additional protocol headers
   * @param [options.status=200] - HTTP status code
   * @param [options.format] - Response format, standard or raw
```

2021-03-23 13:40 UTC, scottinet requested changes

2021-03-24 15:12 UTC, Leodau commented on doc/2/framework/classes/request-response/configure/index.md
> +Allows to directly set internal configuration options.
@scottinet 
Yep, makes sense.
How about 
```suggestion
Allows to configure how the API response should be sent to the requesting client

```

2021-03-26 09:13 UTC, scottinet commented on doc/2/framework/classes/request-response/configure/index.md
> +Allows to directly set internal configuration options.
It's better :+1: 
Suggestion applied.

2021-03-26 09:13 UTC, scottinet approved these changes

2021-03-26 10:30 UTC, merged