Hotfix duplicated cors headers on HTTP Request
kuzzleio/kuzzle pull request #2045
Opened 2021-04-13 15:50 UTC by Shiranuit

## What does this PR do ?
This PR is fixes the unwanted behaviour of CORS headers being duplicated when kuzzle is responding to an HTTP Request.
Duplicating CORS headers on a Response causes the browsers that sent the request to throw a CORS error.

I also added more test cases to avoid this issue in the future.

2021-04-15 17:01 UTC, Leodau approved these changes

2021-04-16 06:51 UTC, Aschen approved these changes

2021-04-16 06:51 UTC, Aschen requested changes
Missing version bump

2021-04-16 08:45 UTC, Shiranuit commented
**Update**: Found some code somewhere else that could duplicate headers, this is now fixed

**Added**:
- `RequestResponse.setHeaders` method now has a new parameter named `ifNotPreset`, if set to `true` only set the header if the header is not already present

2021-04-16 09:06 UTC, Aschen requested changes
You must bump the package version with `npm version patch`

2021-04-16 09:06 UTC, Aschen commented on lib/api/request/requestResponse.ts
> +      Object.keys(headers).forEach(name => {
Avoid the usage of `forEach`, prefer vanilla `for` loop

2021-04-16 09:07 UTC, xbill82 approved these changes

2021-04-16 09:23 UTC, Aschen commented on lib/api/request/requestResponse.ts
> +      for (const name in headers) {
```suggestion
      for (const name of headers) {
```

2021-04-16 09:23 UTC, Aschen approved these changes

2021-04-16 10:13 UTC, merged