Add methods to list and get loaded plugins
kuzzleio/kuzzle pull request #2064
Opened 2021-05-18 07:43 UTC by Aschen

## What does this PR do ?

Adds two methods:
 - `BackendPlugin.list`: list loaded plugins
 - `BackendPlugin.get`: get a loaded plugin instance

2021-05-18 09:41 UTC, scottinet reviewed
It would be nice to have an API route to list plugins too, in the `server` controller.
Something like `server:plugins` for instance.

This would be helpful when trying to get that information, as this would prevent having to scroll through the very lengthy `server:info` response.

2021-05-18 09:43 UTC, scottinet requested changes

2021-05-18 09:43 UTC, scottinet commented on lib/kerror/codes/4-plugin.json
> +          "class": "PluginImplementationError"
I don't think this is a plugin implementation error. Wouldn't a `NotFoundError` be more appropriate?

2021-05-19 06:21 UTC, Aschen commented
> It would be handy to have an API route to list plugins too, in the `server` controller.
> Something like `server:plugins` for instance.
> 
> This would be helpful when trying to get that information, as this would prevent having to scroll through the very lengthy `server:info` response, or resorting to study Kuzzle's logs.

Even if I agree with you that the `server:info` response is quite huge and it's an hassle to scroll it to the plugins part (specially because the API part is at the beginning and very long), I'm not sure that we need another API action just to returns an array of plugin names.

2021-05-19 07:13 UTC, scottinet commented
> Even if I agree with you that the `server:info` response is quite huge and it's an hassle to scroll it to the plugins part (specially because the API part is at the beginning and very long), I'm not sure that we need another API action (with tests, doc, etc) just to returns an array of plugin names.

Well... I had a use case just a few days ago, with a client having trouble to know if a plugin was there or not. 
Again, this is only a "nice to have" feature, but one that will surely prove useful when doing support.

2021-05-19 07:15 UTC, scottinet approved these changes

2021-05-19 10:07 UTC, Aschen commented
@scottinet But why didn't you asked for the response of the `server:info` route ?

Maybe an alternative could be to provide a Kourou command and parse the `server:info` response

2021-05-20 11:15 UTC, xbill82 approved these changes

2021-05-20 11:15 UTC, xbill82 commented on lib/api/controllers/serverController.js
> +
What is this for?

2021-05-23 18:10 UTC, Aschen commented on lib/api/controllers/serverController.js
> +
Leftover

2021-05-26 08:09 UTC, merged