Add minimum rights to connect to AC
kuzzleio/kuzzle pull request #2092
Opened 2021-06-17 14:50 UTC by Aschen

## Description

Add minimum rights required for the anonymous user to connect to the AC

2021-06-17 15:28 UTC, etrousset commented on doc/2/guides/getting-started/run-kuzzle/index.md
> +The minimum rights required for the anonymous user to connect to the Admin Console are:
Je remplacerai anonymous pas a user
```suggestion
The minimum rights required for an user to connect to the Kuzzle Admin Console are:
```

2021-06-21 08:43 UTC, alexandrebouthinon requested changes

2021-06-21 08:43 UTC, alexandrebouthinon commented on doc/2/guides/getting-started/run-kuzzle/index.md
> +The minimum rights required for an user to connect to the Kuzzle Admin Console are:
```suggestion
The minimum rights required by an user to connect to the Kuzzle Admin Console are:
```

2021-06-21 08:44 UTC, alexandrebouthinon commented on doc/2/guides/getting-started/run-kuzzle/index.md
> +The minimum rights required for an user to connect to the Kuzzle Admin Console are:
https://lingohelp.me/preposition-after-adjective/required-for-or-required-of-or-required-by/

2021-06-21 09:15 UTC, alexandrebouthinon approved these changes

2021-06-21 10:30 UTC, Shiranuit approved these changes

2021-06-21 11:58 UTC, merged