Enhance CORS origin verification
kuzzleio/kuzzle pull request #2111
Opened 2021-07-23 15:11 UTC by Shiranuit

:warning: Depends on #2108 

## What does this PR do ?

The goal of this PR is to enhance the verification of a request's origin by adding the possibility of using Regular Expressions instead of just plain string comparison.

To do that a new option has been added to the kuzzlerc `http.accessControlAllowOriginUseRegExp`, this option when set to true converts every strings in `http.accessControlAllowOrigin` into Regular Expressions used to verifiy if a request's origin should be allowed.

This PR also adds a new pipe `funnel:beforeRequestExecution` that can be used to modify / prevent execution of a request, this pipe can be used to verify CORS for example.

2021-08-05 15:39 UTC, xbill82 approved these changes

2021-08-10 12:42 UTC, Aschen commented on lib/api/funnel.js
> +  _isOriginAuthorized(origin) {
```suggestion
  _isOriginAuthorized (origin) {
```

2021-08-10 13:12 UTC, Aschen requested changes

2021-08-10 13:12 UTC, Aschen commented on lib/core/network/entryPoint.js
> +    global.kuzzle.pipe('request:beforeExecution', request)
This should be after the funnel throttle mechanism

2021-08-11 12:03 UTC, Aschen commented on lib/api/funnel.js
> +    global.kuzzle.asyncStore.set('REQUEST', request);
This is set twice, here and line 292 before the triggering of the `request:beforeExecution` event

2021-08-11 16:06 UTC, Shiranuit commented on lib/api/funnel.js
> +  async _preprocessRequest(request, callback) {
I did that to split a bit the logic to improve the readability because the promise chaining was big

2021-08-23 09:42 UTC, merged