Add types for the configuration object
kuzzleio/kuzzle pull request #2175
Opened 2021-10-29 13:05 UTC by matissepage

### Why are we doing this feature?

Write the Typescript type of the Kuzzle config

### How did we make this feature?

avoid config errors, auto-completion, auto-documentation

### Explain: 

create some sub-type like a plugins type for exemple

### How should this be manually tested?

 ```docker-compose up```

2021-10-29 18:16 UTC, Aschen commented on lib/types/config/KuzzleConfiguration.ts
> +export type KuzzleConfiguration = Partial<IKuzzleConfiguration>
I didn't knew that, very nice :+1:

2021-10-29 18:18 UTC, Aschen requested changes
Files in the `types/config` directory should only be related to Kuzzle configuration. Even if you are using types like `RoleDefinition` in the configuration, those types usage are not limited to the configuration file and thus shouldn't be in the directory.

You could organize them in another way, feel free to propose something on this PR discussion before making changes if you want to discuss it beforehand

2021-10-29 18:18 UTC, Aschen commented
You pull request markdown is broken

2021-11-02 13:14 UTC, xbill82 approved these changes

2021-11-19 18:39 UTC, Aschen approved these changes

2021-11-25 17:13 UTC, Aschen requested changes
Last remarks:

- `elasticsearch/StorageService.ts` it should rather be `storageService/StorageServiceElasticsearchConfiguration.ts`
- `InternalCacheConfiguration.ts` it should rather be `internalCache/InternalCacheRedisConfiguration.ts`
- `MemoryStorageConfiguration` it should rather be `publicCache/PublicCacheRedisConfiguration.ts` (slight change in the name to prepare the future)

The file `default.config.js` should converted in Typescript to ensure your type definition match Kuzzle default configuration.

Also, you should use the new created type in the `BackendConfig` class

2021-12-04 18:35 UTC, Aschen requested changes

2021-12-04 18:35 UTC, Aschen commented on lib/config/defaultTsConfig.ts
> +const config: KuzzleConfiguration = {
Nitpicking: a better name could be `defaultConfig`

2021-12-04 18:35 UTC, Aschen commented on lib/config/defaultTsConfig.ts
> +import httpRoutes from './httpRoutes'
Why keeping both the `default.config.js` and this file? You should only have one file for the default configuration and it should be in TS

2021-12-04 18:35 UTC, Aschen commented on lib/config/index.js
> +const KuzzleConfiguration = require('../config/defaultTsConfig');
You should rather import what you need using the destructuring assignment: `const { defaultConfig } = require(...)`.  
It allows to keep consistent names across the codebase

2021-12-04 18:35 UTC, Aschen commented on lib/core/backend/backendConfig.ts
> +import { load } from '../../config/index.js'
This exported function could have a more specific name than `load`

2021-12-20 19:12 UTC, Aschen requested changes

2021-12-20 19:12 UTC, Aschen commented on lib/config/defaultTsConfig.ts
> +          policies: [ { roleID: 'admin'} ]
This property should stay `roleId` to match Kuzzle internal data representation. This comment apply for others occurrences

2021-12-20 19:12 UTC, Aschen commented on lib/config/defaultTsConfig.ts
> +import httpRoutes from '../api/httpRoutes.js';
Why didn't you renamed the file `default.config.ts` ?

2021-12-20 19:12 UTC, Aschen commented on lib/types/ProfileDefinition.ts
> +    roleID: string;
Should be `roleId`

2021-12-20 19:12 UTC, Aschen commented on lib/types/config/KuzzleConfiguration.ts
> +    // }
Comment should be removed

2022-01-03 10:36 UTC, Aschen approved these changes

2022-01-03 10:36 UTC, merged