Add type to limits configuration
kuzzleio/kuzzle pull request #2177
Opened 2021-10-29 13:36 UTC by matissepage

warning Depends on #2163 

**This PR is still in progress**

## What does this PR do ?

Split limits config into another file for more clarity

### How should this be manually tested?

```npm run test:unit```
or
```npm run test```

2021-11-02 13:24 UTC, xbill82 approved these changes

2021-11-04 12:41 UTC, Aschen requested changes
Can you add newline at the end of the files please?
![image](https://user-images.githubusercontent.com/4447392/140315194-8842f3f5-a101-4312-a157-0dbfd6f1022c.png)

2021-11-08 16:18 UTC, alexandrebouthinon approved these changes

2021-11-12 22:13 UTC, Aschen approved these changes

2021-11-12 22:13 UTC, Aschen commented
Can be merged once the conflicts are resolved :+1:

2021-11-19 13:10 UTC, merged