Add type to plugin configuration
kuzzleio/kuzzle pull request #2178
Opened 2021-10-29 14:25 UTC by matissepage

warning Depends on #2163 

**This PR is still in progress**

## What does this PR do ?

Split Plugin config into another file for more clarity

### How should this be manually tested?

```npm run test:unit```
or
```npm run test```

2021-10-29 18:26 UTC, Aschen requested changes
Can you split both plugins config in separate files as well for much clarity?

2021-10-29 18:26 UTC, Aschen commented on lib/types/config/PluginsConfiguration.ts
> +     common: {
Wrong identation

2021-11-04 12:39 UTC, Aschen approved these changes

2021-11-08 16:19 UTC, alexandrebouthinon approved these changes

2021-11-12 14:20 UTC, xbill82 approved these changes

2021-11-12 22:14 UTC, Aschen commented
Can be merged once the conflicts are resolved :+1:

2021-11-12 22:25 UTC, Aschen requested changes

2021-11-12 22:25 UTC, Aschen commented on lib/types/config/PluginsConfiguration.ts
> +    requirePassword: false;
Is it always `false` or a `boolean`

2021-11-19 14:06 UTC, merged