Add type for server config
kuzzleio/kuzzle pull request #2189
Opened 2021-11-04 14:09 UTC by matissepage

warning Depends on #2163 

**This PR is still in progress**

## What does this PR do ?

Add type for server config 

### How should this be manually tested?

```npm run test:unit```
or
```npm run test```

## Other changes

 change the import to make it work

2021-11-04 14:53 UTC, Aschen approved these changes

2021-11-05 09:53 UTC, xbill82 approved these changes

2021-11-08 16:23 UTC, alexandrebouthinon approved these changes

2021-11-08 16:23 UTC, alexandrebouthinon commented on lib/types/index.ts
> +export * from './config/ServerConfiguration';
```suggestion
export * from './config/ServerConfiguration';

```

2021-11-12 22:23 UTC, Aschen requested changes

2021-11-12 22:23 UTC, Aschen commented on lib/types/config/ServerConfiguration.ts
> +    accessLogFormat: string;
This is `"combined" | "logstash"`

2021-11-12 22:23 UTC, Aschen commented on lib/types/config/ServerConfiguration.ts
> +        enabled: true
Is this always `true` or `boolean` ? Also you have an indentation problem starting here

2021-11-12 22:23 UTC, Aschen commented on lib/types/config/ServerConfiguration.ts
> +                realtimeNotifications: boolean
Wrong indentation

2021-11-19 18:38 UTC, Aschen approved these changes

2021-11-25 16:22 UTC, merged