Support M1 chip
kuzzleio/kuzzle pull request #2253
Opened 2022-01-13 15:47 UTC by clementbolin

Depend [Support M1 chip #63](https://github.com/kuzzleio/kuzzle-containers/pull/63)

## What does this PR do ?

Support Kuzzle core-dev for M1 chip.
I added a `kuzzle_installer` service, in order to install the dependencies directly in the container without getting any error

### How should this be manually tested?

docker-compose up

2022-01-13 18:05 UTC, Aschen requested changes
With this PR, dependencies have to be rebuilt each time we run the Docker Compose stack.

2022-01-13 18:05 UTC, Aschen commented on docker/scripts/run-dev.sh
> +    # npm ci --unsafe-perm
Leftover?

2022-01-15 04:13 UTC, Aschen requested changes
Can you add a section in the README about m1 chip and installing dependencies from inside the container?

2022-01-17 10:19 UTC, xbill82 approved these changes

2022-01-20 13:26 UTC, alexandrebouthinon approved these changes

2022-01-20 13:39 UTC, merged