Fix typo for openapi (document-get)
kuzzleio/kuzzle pull request #2305
Opened 2022-04-01 13:12 UTC by ChillPC

2022-04-04 07:21 UTC, Aschen requested changes
This PR should be assigned to you and have the appropriate label before being merged.

Also, nitpicking on the title, it should avoid parenthesis and clearly state whats it's modifying (on this you are almost good :+1: )

2022-04-04 13:00 UTC, Aschen commented
Last nitpicking:
 - we use the "API action" term instead of "API Call", "method call", "api route", etc
 - we usually represents API action with `<controller>:<action>`

`Fix typo for openapi for the document:get API action`

2022-04-13 15:59 UTC, Shiranuit approved these changes

2022-04-14 10:04 UTC, Aschen approved these changes

2022-04-14 11:48 UTC, merged