Fix race condition when creating index hidden indice
kuzzleio/kuzzle pull request #2328
Opened 2022-04-13 13:52 UTC by Aschen

## What does this PR do ?

When creating a new index, an special ES indice is created (`&<index>._kuzzle_keep`) to reserve the index name.

If `index:create` is called in the same time, then we have a race condition when trying to create this indice since it could have been created between the check for existence and the creation.

This PR use a mutex to prevent such race conditions

2022-04-13 14:01 UTC, Shiranuit commented on lib/service/storage/elasticsearch.js
shouldn't the mutex be acquired before deleting the indice in ES ?

2022-04-13 14:09 UTC, Shiranuit requested changes

2022-04-13 14:09 UTC, Shiranuit commented on lib/service/storage/elasticsearch.js
I see the mutex is acquired after deleting the index in ES, shouldn't the mutex be acquired before ?

2022-04-13 15:46 UTC, Shiranuit commented on lib/service/storage/elasticsearch.js
>          await this._createHiddenCollection(index);
A bit tricky but `deleteCollection` uses the mutex `hiddenCollection/${index}` then later calls `_createHiddenCollection` which also use the mutex `hiddenCollection/${index}` which is already locked at the moment it is called, which causes your test to be stuck in an infinite loop

2022-04-14 22:16 UTC, Shiranuit approved these changes

2022-04-16 18:41 UTC, clementbolin approved these changes

2022-04-19 10:14 UTC, merged