Mappings update should trigger a reindex
kuzzleio/kuzzle pull request #2333
Opened 2022-04-16 10:46 UTC by clementbolin

## What does this PR do ?

### How should this be manually tested?

  - Step 1 :
  - Step 2 :
  - Step 3 :

### Other changes

### Boyscout

2022-04-27 12:27 UTC, Shiranuit requested changes

2022-04-27 12:27 UTC, Shiranuit commented on features/CollectionController.feature
> +  Scenario: Update a collection and search document (dyanmic false)
```suggestion
  Scenario: Update a collection and search document (dynamic false)
```

2022-04-27 12:27 UTC, Shiranuit commented on lib/service/storage/elasticsearch.js
> +        if (previousMappings.dynamic === 'false' && (await this._client.search(esRequest)).body.hits.hits.length > 0) {
If think it's better to call `count` than `search` if you just want to know if there are documents to update

Side note:
Avoid putting long calls with chained property access like this in condition for clarity `await this._client.search(esRequest)).body.hits.hits.length` prefer storing the result in a const variable.
Conditions that are too long and uses `&&` or `||` should be splitted on multiple lines like so
```js
const documentsCount = await this._client.search(esRequest)).body.hits.hits.length;
if ( previousMappings.dynamic === 'false'
  && documentsCount > 0
) {
```

2022-04-27 12:27 UTC, Shiranuit commented on features/CollectionController.feature
> +      """
It's good but you also need to verify that the search does not match the field `age` before updating the mapping and triggering the reindex

2023-01-02 14:21 UTC, Aschen commented
Stale PR

2023-01-02 14:21 UTC, closed without merging