Remove import mappings lock on `auth:resetDatabase` action
kuzzleio/kuzzle pull request #2341
Opened 2022-04-25 12:20 UTC by ChillPC

#2297

2022-04-28 13:48 UTC, Aschen requested changes

2022-04-28 13:48 UTC, Aschen commented on lib/kuzzle/kuzzle.ts
> +    importTypes.forEach(async importType => {
We try to avoid `forEach` loop because they are not respecting the synchronicity of the `await` keyword

2022-04-28 13:48 UTC, Aschen commented on lib/kuzzle/kuzzle.ts
> +            _.set(importPayload, ['toSupport', 'fixtures'], toSupport.fixtures);
You should use the dot notation to access object elements
```suggestion
            _.set(importPayload, 'toSupport.fixtures', toSupport.fixtures);
```

2022-04-28 13:48 UTC, Aschen commented on lib/kuzzle/kuzzle.ts
> +        const importPayloadHash = sha256(JSON.stringify(importPayload));
You should use `stable-json-stringify` here to ensure the key order will be the same (even if with Node.js there is very little chances to have a key order inconsistency)

2022-04-28 13:48 UTC, Aschen commented on lib/kuzzle/kuzzle.ts
> +        const initialized = existingHash && existingHash === importPayloadHash;
Can be simply
```suggestion
        const initialized = existingHash === importPayloadHash;
```

2022-04-28 17:05 UTC, Aschen requested changes
Missing unit tests for this PR

2022-04-29 11:00 UTC, Aschen commented on test/kuzzle/kuzzle.test.js
> +      should(kuzzle.ask).be.calledWithMatch(
Same comment, the ask function should have been called with 3 args

2022-05-02 10:09 UTC, Aschen approved these changes

2022-05-03 12:10 UTC, OlivierCavadenti approved these changes

2022-05-09 08:50 UTC, Shiranuit approved these changes

2022-05-09 09:32 UTC, merged