Support Koncorde syntax for document:count
kuzzleio/kuzzle pull request #2392
Opened 2022-10-19 15:34 UTC by OlivierCavadenti

## What does this PR do ?

Support [Koncorde filters syntax](https://docs.kuzzle.io/core/2/guides/main-concepts/querying/#koncorde-query) for querying like other search methods.

### How should this be manually tested?

Use Koncorde filters in query parameters and set "lang" parameter to "koncorde".

2022-10-24 15:41 UTC, Shiranuit requested changes

2022-10-24 15:41 UTC, Shiranuit commented on doc/2/api/controllers/document/count/index.md
> +- `lang`: specify the query language to use. By default, it's `elasticsearch` but `koncorde` can also be used. <SinceBadge version="2.8.0"/>
```suggestion
- `lang`: specify the query language to use. By default, it's `elasticsearch` but `koncorde` can also be used. <SinceBadge version="auto-version"/>
```

2022-10-24 15:41 UTC, Shiranuit commented on doc/2/api/controllers/document/count/index.md
> +- `lang`: specify the query language to use. By default, it's `elasticsearch` but `koncorde` can also be used. <SinceBadge version="2.8.0"/>
You should use `auto-version` this way the version is replaced  with the proper value when released.

2022-10-31 16:19 UTC, kuzzle commented
<!--
  1 failure:  Found some issues !
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Found some issues !</td>
    </tr>
  </tbody>
</table>



## Executed Checks

### :heavy_check_mark: Branch Merge Check



### :x: Changelog Tag Check

Pull Requests must have a `changelog:XXX` label.
If you want to allow this PR to not have a changelog tag, add the following line to the PR body:


```
ci-no-changelog-tag
```

### :heavy_check_mark: PR Body Check


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4a04369c04f72dd6f4a3e352d6f3993762c77082
</p>

2022-10-31 20:21 UTC, Aschen approved these changes

2022-11-07 08:38 UTC, Shiranuit approved these changes

2022-11-07 11:01 UTC, Aschen commented
You can comment the dead link check job

2022-11-17 18:50 UTC, merged