Elasticsearch 8
kuzzleio/kuzzle pull request #2548
Opened 2024-08-28 07:45 UTC by rolljee

## What does this PR do ?

* This PR adds the already tested Elasticsearch 8 Support into the standard workflow

### How should this be manually tested?

  - Step 1 :
  - Step 2 :
  - Step 3 :

### Other changes

### Boyscout

2024-08-28 09:23 UTC, Kuruyia requested changes

2024-08-28 09:23 UTC, Kuruyia commented on lib/service/storage/commons/queryTranslator.js
Because KDM uses it directly, we'll probably want to export the `QueryTranslator` class to avoid breaking it. We'll still need to update the import in KDM tho': https://github.com/kuzzleio/kuzzle-device-manager/blob/9990e57db9bc845d6d6df1e64bed05e88e00f377/lib/modules/measure/MeasureExporter.ts#L5-L6

2024-08-28 11:59 UTC, fmauNeko approved these changes

2024-08-28 13:05 UTC, rolljee commented on lib/service/storage/commons/queryTranslator.js
I'll add it

2024-08-28 14:03 UTC, Kuruyia approved these changes

2024-08-30 06:26 UTC, Kuruyia commented
Please squash this PR when merging :)

2024-09-04 12:51 UTC, merged

2024-09-13 07:49 UTC, kuzzle commented
:tada: This PR is included in version 2.32.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/kuzzle/v/2.32.0-beta.1)
- [GitHub release](https://github.com/kuzzleio/kuzzle/releases/tag/v2.32.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-10-02 06:02 UTC, kuzzle commented
:tada: This PR is included in version 2.32.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/kuzzle/v/2.32.0)
- [GitHub release](https://github.com/kuzzleio/kuzzle/releases/tag/v2.32.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: